export const ROUTES = {
  overview: '/',
  people: '/people',
  personDetail: (id: number | string) => `/people/${id}`,
  brigades: '/brigades',
  brigadeDetail: (id: number | string) => `/brigades/${id}`,
  sites: '/sites',
  siteDetail: (id: number | string) => `/sites/${id}`,
  entry: '/entry',
  company: '/company',
  summary: '/summary',
  analytics: '/analytics',
  analyticsDrawingDetail: (id: number | string) => `/analytics/drawings/${id}`,
  settings: '/settings',
  printDebtSummary: '/print/debt-summary',
  printReport: '/print/report',
  printSummary: '/print/summary',
  printPerson: (id: number | string) => `/print/person/${id}`,
  printSite: (id: number | string) => `/print/site/${id}`,
  printBrigade: (id: number | string) => `/print/brigade/${id}`,
} as const
